INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (1,'AC','Acre');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (2,'AL','Alagoas');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (3,'AM','Amazonas');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (4,'AP','Amapá');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (5,'BA','Bahia');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (6,'CE','Ceará');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (7,'DF','Distrito Federal');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (8,'ES','Espírito Santo');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (9,'GO','Goiás');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (10,'MA','Maranhão');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (11,'MG','Minas Gerais');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (12,'MS','Mato Grosso do Sul');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (13,'MT','Mato Grosso');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (14,'PA','Pará');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (15,'PB','Paraíba');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (16,'PE','Pernambuco');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (17,'PI','Piauí');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (18,'PR','Paraná');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (19,'RJ','Rio de Janeiro');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (20,'RN','Rio Grande do Norte');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (21,'RO','Rondônia');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (22,'RR','Roraima');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (23,'RS','Rio Grande do Sul');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (24,'SC','Santa Catarina');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (25,'SE','Sergipe');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (26,'SP','São Paulo');
INSERT INTO `unidade_federativa` (`id`,`sigla`,`nome`) VALUES (27,'TO','Tocantins');
