INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (1,'Afonso Cláudio',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (2,'Água Doce do Norte',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (3,'Águia Branca',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (4,'Alegre',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (5,'Alfredo Chaves',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (6,'Alto Rio Novo',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (7,'Anchieta',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (8,'Apiacá',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (9,'Aracruz',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (10,'Atilio Vivacqua',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (11,'Baixo Guandu',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (12,'Barra de São Francisco',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (13,'Boa Esperança',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (14,'Bom Jesus do Norte',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (15,'Brejetuba',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (16,'Cachoeiro de Itapemirim',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (17,'Cariacica',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (18,'Castelo',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (19,'Colatina',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (20,'Conceição da Barra',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (21,'Conceição do Castelo',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (22,'Divino de São Lourenço',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (23,'Domingos Martins',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (24,'Dores do Rio Preto',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (25,'Ecoporanga',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (26,'Fundão',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (27,'Governador Lindenberg',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (28,'Guaçuí',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (29,'Guarapari',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (30,'Ibatiba',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (31,'Ibiraçu',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (32,'Ibitirama',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (33,'Iconha',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (34,'Irupi',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (35,'Itaguaçu',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (36,'Itapemirim',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (37,'Itarana',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (38,'Iúna',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (39,'Jaguaré',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (40,'Jerônimo Monteiro',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (41,'João Neiva',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (42,'Laranja da Terra',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (43,'Linhares',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (44,'Mantenópolis',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (45,'Marataízes',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (46,'Marechal Floriano',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (47,'Marilândia',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (48,'Mimoso do Sul',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (49,'Montanha',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (50,'Mucurici',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (51,'Muniz Freire',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (52,'Muqui',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (53,'Nova Venécia',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (54,'Pancas',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (55,'Pedro Canário',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (56,'Pinheiros',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (57,'Piúma',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (58,'Ponto Belo',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (59,'Presidente Kennedy',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (60,'Rio Bananal',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (61,'Rio Novo do Sul',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (62,'Santa Leopoldina',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (63,'Santa Maria de Jetibá',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (64,'Santa Teresa',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (65,'São Domingos do Norte',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (66,'São Gabriel da Palha',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (67,'São José do Calçado',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (68,'São Mateus',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (69,'São Roque do Canaã',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (70,'Serra',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (71,'Sooretama',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (72,'Vargem Alta',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (73,'Venda Nova do Imigrante',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (74,'Viana',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (75,'Vila Pavão',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (76,'Vila Valério',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (77,'Vila Velha',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (78,'Vitória',8);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (79,'Acrelândia',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (80,'Assis Brasil',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (81,'Brasiléia',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (82,'Bujari',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (83,'Capixaba',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (84,'Cruzeiro do Sul',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (85,'Epitaciolândia',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (86,'Feijó',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (87,'Jordão',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (88,'Mâncio Lima',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (89,'Manoel Urbano',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (90,'Marechal Thaumaturgo',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (91,'Plácido de Castro',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (92,'Porto Acre',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (93,'Porto Walter',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (94,'Rio Branco',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (95,'Rodrigues Alves',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (96,'Santa Rosa do Purus',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (97,'Sena Madureira',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (98,'Senador Guiomard',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (99,'Tarauacá',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (100,'Xapuri',1);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (101,'Água Branca',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (102,'Anadia',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (103,'Arapiraca',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (104,'Atalaia',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (105,'Barra de Santo Antônio',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (106,'Barra de São Miguel',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (107,'Batalha',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (108,'Belém',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (109,'Belo Monte',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (110,'Boca da Mata',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (111,'Branquinha',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (112,'Cacimbinhas',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (113,'Cajueiro',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (114,'Campestre',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (115,'Campo Alegre',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (116,'Campo Grande',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (117,'Canapi',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (118,'Capela',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (119,'Carneiros',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (120,'Chã Preta',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (121,'Coité do Nóia',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (122,'Colônia Leopoldina',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (123,'Coqueiro Seco',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (124,'Coruripe',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (125,'Craíbas',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (126,'Delmiro Gouveia',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (127,'Dois Riachos',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (128,'Estrela de Alagoas',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (129,'Feira Grande',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (130,'Feliz Deserto',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (131,'Flexeiras',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (132,'Girau do Ponciano',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (133,'Ibateguara',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (134,'Igaci',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (135,'Igreja Nova',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (136,'Inhapi',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (137,'Jacaré dos Homens',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (138,'Jacuípe',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (139,'Japaratinga',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (140,'Jaramataia',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (141,'Jequiá da Praia',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (142,'Joaquim Gomes',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (143,'Jundiá',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (144,'Junqueiro',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (145,'Lagoa da Canoa',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (146,'Limoeiro de Anadia',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (147,'Maceió',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (148,'Major Isidoro',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (149,'Mar Vermelho',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (150,'Maragogi',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (151,'Maravilha',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (152,'Marechal Deodoro',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (153,'Maribondo',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (154,'Mata Grande',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (155,'Matriz de Camaragibe',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (156,'Messias',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (157,'Minador do Negrão',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (158,'Monteirópolis',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (159,'Murici',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (160,'Novo Lino',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (161,'Olho d`Água das Flores',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (162,'Olho d`Água do Casado',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (163,'Olho d`Água Grande',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (164,'Olivença',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (165,'Ouro Branco',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (166,'Palestina',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (167,'Palmeira dos Índios',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (168,'Pão de Açúcar',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (169,'Pariconha',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (170,'Paripueira',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (171,'Passo de Camaragibe',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (172,'Paulo Jacinto',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (173,'Penedo',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (174,'Piaçabuçu',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (175,'Pilar',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (176,'Pindoba',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (177,'Piranhas',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (178,'Poço das Trincheiras',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (179,'Porto Calvo',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (180,'Porto de Pedras',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (181,'Porto Real do Colégio',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (182,'Quebrangulo',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (183,'Rio Largo',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (184,'Roteiro',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (185,'Santa Luzia do Norte',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (186,'Santana do Ipanema',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (187,'Santana do Mundaú',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (188,'São Brás',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (189,'São José da Laje',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (190,'São José da Tapera',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (191,'São Luís do Quitunde',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (192,'São Miguel dos Campos',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (193,'São Miguel dos Milagres',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (194,'São Sebastião',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (195,'Satuba',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (196,'Senador Rui Palmeira',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (197,'Tanque d`Arca',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (198,'Taquarana',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (199,'Teotônio Vilela',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (200,'Traipu',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (201,'União dos Palmares',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (202,'Viçosa',2);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (203,'Amapá',4);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (204,'Calçoene',4);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (205,'Cutias',4);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (206,'Ferreira Gomes',4);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (207,'Itaubal',4);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (208,'Laranjal do Jari',4);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (209,'Macapá',4);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (210,'Mazagão',4);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (211,'Oiapoque',4);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (212,'Pedra Branca do Amaparí',4);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (213,'Porto Grande',4);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (214,'Pracuúba',4);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (215,'Santana',4);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (216,'Serra do Navio',4);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (217,'Tartarugalzinho',4);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (218,'Vitória do Jari',4);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (219,'Alvarães',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (220,'Amaturá',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (221,'Anamã',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (222,'Anori',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (223,'Apuí',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (224,'Atalaia do Norte',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (225,'Autazes',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (226,'Barcelos',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (227,'Barreirinha',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (228,'Benjamin Constant',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (229,'Beruri',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (230,'Boa Vista do Ramos',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (231,'Boca do Acre',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (232,'Borba',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (233,'Caapiranga',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (234,'Canutama',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (235,'Carauari',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (236,'Careiro',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (237,'Careiro da Várzea',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (238,'Coari',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (239,'Codajás',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (240,'Eirunepé',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (241,'Envira',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (242,'Fonte Boa',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (243,'Guajará',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (244,'Humaitá',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (245,'Ipixuna',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (246,'Iranduba',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (247,'Itacoatiara',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (248,'Itamarati',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (249,'Itapiranga',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (250,'Japurá',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (251,'Juruá',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (252,'Jutaí',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (253,'Lábrea',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (254,'Manacapuru',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (255,'Manaquiri',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (256,'Manaus',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (257,'Manicoré',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (258,'Maraã',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (259,'Maués',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (260,'Nhamundá',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (261,'Nova Olinda do Norte',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (262,'Novo Airão',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (263,'Novo Aripuanã',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (264,'Parintins',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (265,'Pauini',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (266,'Presidente Figueiredo',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (267,'Rio Preto da Eva',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (268,'Santa Isabel do Rio Negro',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (269,'Santo Antônio do Içá',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (270,'São Gabriel da Cachoeira',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (271,'São Paulo de Olivença',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (272,'São Sebastião do Uatumã',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (273,'Silves',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (274,'Tabatinga',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (275,'Tapauá',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (276,'Tefé',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (277,'Tonantins',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (278,'Uarini',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (279,'Urucará',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (280,'Urucurituba',3);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (281,'Abaíra',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (282,'Abaré',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (283,'Acajutiba',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (284,'Adustina',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (285,'Água Fria',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (286,'Aiquara',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (287,'Alagoinhas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (288,'Alcobaça',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (289,'Almadina',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (290,'Amargosa',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (291,'Amélia Rodrigues',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (292,'América Dourada',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (293,'Anagé',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (294,'Andaraí',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (295,'Andorinha',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (296,'Angical',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (297,'Anguera',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (298,'Antas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (299,'Antônio Cardoso',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (300,'Antônio Gonçalves',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (301,'Aporá',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (302,'Apuarema',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (303,'Araças',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (304,'Aracatu',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (305,'Araci',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (306,'Aramari',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (307,'Arataca',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (308,'Aratuípe',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (309,'Aurelino Leal',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (310,'Baianópolis',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (311,'Baixa Grande',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (312,'Banzaê',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (313,'Barra',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (314,'Barra da Estiva',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (315,'Barra do Choça',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (316,'Barra do Mendes',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (317,'Barra do Rocha',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (318,'Barreiras',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (319,'Barro Alto',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (320,'Barro Preto (antigo Gov. Lomanto Jr.)',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (321,'Barrocas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (322,'Belmonte',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (323,'Belo Campo',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (324,'Biritinga',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (325,'Boa Nova',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (326,'Boa Vista do Tupim',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (327,'Bom Jesus da Lapa',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (328,'Bom Jesus da Serra',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (329,'Boninal',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (330,'Bonito',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (331,'Boquira',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (332,'Botuporã',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (333,'Brejões',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (334,'Brejolândia',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (335,'Brotas de Macaúbas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (336,'Brumado',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (337,'Buerarema',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (338,'Buritirama',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (339,'Caatiba',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (340,'Cabaceiras do Paraguaçu',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (341,'Cachoeira',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (342,'Caculé',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (343,'Caém',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (344,'Caetanos',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (345,'Caetité',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (346,'Cafarnaum',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (347,'Cairu',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (348,'Caldeirão Grande',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (349,'Camacan',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (350,'Camaçari',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (351,'Camamu',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (352,'Campo Alegre de Lourdes',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (353,'Campo Formoso',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (354,'Canápolis',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (355,'Canarana',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (356,'Canavieiras',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (357,'Candeal',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (358,'Candeias',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (359,'Candiba',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (360,'Cândido Sales',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (361,'Cansanção',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (362,'Canudos',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (363,'Capela do Alto Alegre',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (364,'Capim Grosso',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (365,'Caraíbas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (366,'Caravelas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (367,'Cardeal da Silva',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (368,'Carinhanha',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (369,'Casa Nova',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (370,'Castro Alves',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (371,'Catolândia',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (372,'Catu',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (373,'Caturama',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (374,'Central',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (375,'Chorrochó',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (376,'Cícero Dantas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (377,'Cipó',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (378,'Coaraci',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (379,'Cocos',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (380,'Conceição da Feira',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (381,'Conceição do Almeida',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (382,'Conceição do Coité',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (383,'Conceição do Jacuípe',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (384,'Conde',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (385,'Condeúba',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (386,'Contendas do Sincorá',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (387,'Coração de Maria',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (388,'Cordeiros',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (389,'Coribe',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (390,'Coronel João Sá',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (391,'Correntina',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (392,'Cotegipe',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (393,'Cravolândia',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (394,'Crisópolis',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (395,'Cristópolis',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (396,'Cruz das Almas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (397,'Curaçá',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (398,'Dário Meira',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (399,'Dias d`Ávila',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (400,'Dom Basílio',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (401,'Dom Macedo Costa',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (402,'Elísio Medrado',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (403,'Encruzilhada',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (404,'Entre Rios',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (405,'Érico Cardoso',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (406,'Esplanada',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (407,'Euclides da Cunha',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (408,'Eunápolis',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (409,'Fátima',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (410,'Feira da Mata',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (411,'Feira de Santana',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (412,'Filadélfia',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (413,'Firmino Alves',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (414,'Floresta Azul',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (415,'Formosa do Rio Preto',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (416,'Gandu',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (417,'Gavião',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (418,'Gentio do Ouro',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (419,'Glória',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (420,'Gongogi',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (421,'Governador Mangabeira',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (422,'Guajeru',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (423,'Guanambi',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (424,'Guaratinga',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (425,'Heliópolis',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (426,'Iaçu',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (427,'Ibiassucê',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (428,'Ibicaraí',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (429,'Ibicoara',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (430,'Ibicuí',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (431,'Ibipeba',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (432,'Ibipitanga',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (433,'Ibiquera',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (434,'Ibirapitanga',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (435,'Ibirapuã',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (436,'Ibirataia',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (437,'Ibitiara',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (438,'Ibititá',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (439,'Ibotirama',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (440,'Ichu',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (441,'Igaporã',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (442,'Igrapiúna',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (443,'Iguaí',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (444,'Ilhéus',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (445,'Inhambupe',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (446,'Ipecaetá',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (447,'Ipiaú',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (448,'Ipirá',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (449,'Ipupiara',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (450,'Irajuba',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (451,'Iramaia',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (452,'Iraquara',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (453,'Irará',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (454,'Irecê',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (455,'Itabela',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (456,'Itaberaba',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (457,'Itabuna',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (458,'Itacaré',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (459,'Itaeté',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (460,'Itagi',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (461,'Itagibá',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (462,'Itagimirim',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (463,'Itaguaçu da Bahia',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (464,'Itaju do Colônia',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (465,'Itajuípe',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (466,'Itamaraju',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (467,'Itamari',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (468,'Itambé',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (469,'Itanagra',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (470,'Itanhém',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (471,'Itaparica',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (472,'Itapé',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (473,'Itapebi',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (474,'Itapetinga',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (475,'Itapicuru',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (476,'Itapitanga',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (477,'Itaquara',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (478,'Itarantim',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (479,'Itatim',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (480,'Itiruçu',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (481,'Itiúba',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (482,'Itororó',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (483,'Ituaçu',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (484,'Ituberá',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (485,'Iuiú',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (486,'Jaborandi',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (487,'Jacaraci',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (488,'Jacobina',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (489,'Jaguaquara',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (490,'Jaguarari',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (491,'Jaguaripe',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (492,'Jandaíra',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (493,'Jequié',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (494,'Jeremoabo',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (495,'Jiquiriçá',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (496,'Jitaúna',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (497,'João Dourado',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (498,'Juazeiro',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (499,'Jucuruçu',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (500,'Jussara',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (501,'Jussari',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (502,'Jussiape',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (503,'Lafaiete Coutinho',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (504,'Lagoa Real',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (505,'Laje',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (506,'Lajedão',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (507,'Lajedinho',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (508,'Lajedo do Tabocal',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (509,'Lamarão',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (510,'Lapão',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (511,'Lauro de Freitas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (512,'Lençóis',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (513,'Licínio de Almeida',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (514,'Livramento de Nossa Senhora',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (515,'Luís Eduardo Magalhães',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (516,'Macajuba',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (517,'Macarani',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (518,'Macaúbas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (519,'Macururé',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (520,'Madre de Deus',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (521,'Maetinga',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (522,'Maiquinique',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (523,'Mairi',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (524,'Malhada',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (525,'Malhada de Pedras',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (526,'Manoel Vitorino',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (527,'Mansidão',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (528,'Maracás',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (529,'Maragogipe',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (530,'Maraú',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (531,'Marcionílio Souza',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (532,'Mascote',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (533,'Mata de São João',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (534,'Matina',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (535,'Medeiros Neto',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (536,'Miguel Calmon',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (537,'Milagres',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (538,'Mirangaba',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (539,'Mirante',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (540,'Monte Santo',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (541,'Morpará',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (542,'Morro do Chapéu',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (543,'Mortugaba',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (544,'Mucugê',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (545,'Mucuri',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (546,'Mulungu do Morro',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (547,'Mundo Novo',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (548,'Muniz Ferreira',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (549,'Muquém de São Francisco',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (550,'Muritiba',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (551,'Mutuípe',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (552,'Nazaré',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (553,'Nilo Peçanha',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (554,'Nordestina',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (555,'Nova Canaã',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (556,'Nova Fátima',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (557,'Nova Ibiá',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (558,'Nova Itarana',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (559,'Nova Redenção',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (560,'Nova Soure',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (561,'Nova Viçosa',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (562,'Novo Horizonte',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (563,'Novo Triunfo',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (564,'Olindina',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (565,'Oliveira dos Brejinhos',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (566,'Ouriçangas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (567,'Ourolândia',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (568,'Palmas de Monte Alto',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (569,'Palmeiras',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (570,'Paramirim',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (571,'Paratinga',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (572,'Paripiranga',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (573,'Pau Brasil',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (574,'Paulo Afonso',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (575,'Pé de Serra',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (576,'Pedrão',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (577,'Pedro Alexandre',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (578,'Piatã',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (579,'Pilão Arcado',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (580,'Pindaí',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (581,'Pindobaçu',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (582,'Pintadas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (583,'Piraí do Norte',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (584,'Piripá',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (585,'Piritiba',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (586,'Planaltino',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (587,'Planalto',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (588,'Poções',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (589,'Pojuca',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (590,'Ponto Novo',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (591,'Porto Seguro',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (592,'Potiraguá',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (593,'Prado',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (594,'Presidente Dutra',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (595,'Presidente Jânio Quadros',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (596,'Presidente Tancredo Neves',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (597,'Queimadas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (598,'Quijingue',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (599,'Quixabeira',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (600,'Rafael Jambeiro',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (601,'Remanso',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (602,'Retirolândia',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (603,'Riachão das Neves',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (604,'Riachão do Jacuípe',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (605,'Riacho de Santana',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (606,'Ribeira do Amparo',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (607,'Ribeira do Pombal',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (608,'Ribeirão do Largo',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (609,'Rio de Contas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (610,'Rio do Antônio',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (611,'Rio do Pires',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (612,'Rio Real',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (613,'Rodelas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (614,'Ruy Barbosa',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (615,'Salinas da Margarida',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (616,'Salvador',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (617,'Santa Bárbara',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (618,'Santa Brígida',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (619,'Santa Cruz Cabrália',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (620,'Santa Cruz da Vitória',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (621,'Santa Inês',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (622,'Santa Luzia',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (623,'Santa Maria da Vitória',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (624,'Santa Rita de Cássia',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (625,'Santa Teresinha',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (626,'Santaluz',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (627,'Santana',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (628,'Santanópolis',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (629,'Santo Amaro',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (630,'Santo Antônio de Jesus',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (631,'Santo Estêvão',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (632,'São Desidério',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (633,'São Domingos',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (634,'São Felipe',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (635,'São Félix',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (636,'São Félix do Coribe',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (637,'São Francisco do Conde',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (638,'São Gabriel',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (639,'São Gonçalo dos Campos',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (640,'São José da Vitória',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (641,'São José do Jacuípe',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (642,'São Miguel das Matas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (643,'São Sebastião do Passé',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (644,'Sapeaçu',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (645,'Sátiro Dias',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (646,'Saubara',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (647,'Saúde',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (648,'Seabra',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (649,'Sebastião Laranjeiras',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (650,'Senhor do Bonfim',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (651,'Sento Sé',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (652,'Serra do Ramalho',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (653,'Serra Dourada',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (654,'Serra Preta',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (655,'Serrinha',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (656,'Serrolândia',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (657,'Simões Filho',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (658,'Sítio do Mato',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (659,'Sítio do Quinto',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (660,'Sobradinho',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (661,'Souto Soares',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (662,'Tabocas do Brejo Velho',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (663,'Tanhaçu',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (664,'Tanque Novo',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (665,'Tanquinho',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (666,'Taperoá',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (667,'Tapiramutá',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (668,'Teixeira de Freitas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (669,'Teodoro Sampaio',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (670,'Teofilândia',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (671,'Teolândia',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (672,'Terra Nova',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (673,'Tremedal',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (674,'Tucano',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (675,'Uauá',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (676,'Ubaíra',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (677,'Ubaitaba',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (678,'Ubatã',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (679,'Uibaí',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (680,'Umburanas',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (681,'Una',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (682,'Urandi',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (683,'Uruçuca',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (684,'Utinga',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (685,'Valença',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (686,'Valente',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (687,'Várzea da Roça',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (688,'Várzea do Poço',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (689,'Várzea Nova',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (690,'Varzedo',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (691,'Vera Cruz',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (692,'Vereda',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (693,'Vitória da Conquista',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (694,'Wagner',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (695,'Wanderley',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (696,'Wenceslau Guimarães',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (697,'Xique-Xique',5);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (698,'Abaiara',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (699,'Acarape',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (700,'Acaraú',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (701,'Acopiara',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (702,'Aiuaba',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (703,'Alcântaras',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (704,'Altaneira',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (705,'Alto Santo',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (706,'Amontada',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (707,'Antonina do Norte',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (708,'Apuiarés',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (709,'Aquiraz',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (710,'Aracati',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (711,'Aracoiaba',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (712,'Ararendá',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (713,'Araripe',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (714,'Aratuba',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (715,'Arneiroz',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (716,'Assaré',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (717,'Aurora',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (718,'Baixio',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (719,'Banabuiú',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (720,'Barbalha',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (721,'Barreira',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (722,'Barro',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (723,'Barroquinha',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (724,'Baturité',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (725,'Beberibe',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (726,'Bela Cruz',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (727,'Boa Viagem',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (728,'Brejo Santo',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (729,'Camocim',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (730,'Campos Sales',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (731,'Canindé',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (732,'Capistrano',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (733,'Caridade',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (734,'Cariré',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (735,'Caririaçu',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (736,'Cariús',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (737,'Carnaubal',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (738,'Cascavel',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (739,'Catarina',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (740,'Catunda',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (741,'Caucaia',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (742,'Cedro',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (743,'Chaval',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (744,'Choró',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (745,'Chorozinho',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (746,'Coreaú',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (747,'Crateús',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (748,'Crato',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (749,'Croatá',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (750,'Cruz',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (751,'Deputado Irapuan Pinheiro',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (752,'Ererê',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (753,'Eusébio',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (754,'Farias Brito',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (755,'Forquilha',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (756,'Fortaleza',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (757,'Fortim',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (758,'Frecheirinha',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (759,'General Sampaio',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (760,'Graça',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (761,'Granja',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (762,'Granjeiro',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (763,'Groaíras',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (764,'Guaiúba',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (765,'Guaraciaba do Norte',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (766,'Guaramiranga',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (767,'Hidrolândia',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (768,'Horizonte',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (769,'Ibaretama',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (770,'Ibiapina',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (771,'Ibicuitinga',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (772,'Icapuí',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (773,'Icó',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (774,'Iguatu',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (775,'Independência',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (776,'Ipaporanga',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (777,'Ipaumirim',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (778,'Ipu',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (779,'Ipueiras',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (780,'Iracema',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (781,'Irauçuba',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (782,'Itaiçaba',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (783,'Itaitinga',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (784,'Itapagé',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (785,'Itapipoca',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (786,'Itapiúna',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (787,'Itarema',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (788,'Itatira',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (789,'Jaguaretama',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (790,'Jaguaribara',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (791,'Jaguaribe',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (792,'Jaguaruana',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (793,'Jardim',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (794,'Jati',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (795,'Jijoca de Jericoacoara',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (796,'Juazeiro do Norte',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (797,'Jucás',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (798,'Lavras da Mangabeira',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (799,'Limoeiro do Norte',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (800,'Madalena',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (801,'Maracanaú',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (802,'Maranguape',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (803,'Marco',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (804,'Martinópole',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (805,'Massapê',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (806,'Mauriti',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (807,'Meruoca',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (808,'Milagres',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (809,'Milhã',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (810,'Miraíma',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (811,'Missão Velha',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (812,'Mombaça',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (813,'Monsenhor Tabosa',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (814,'Morada Nova',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (815,'Moraújo',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (816,'Morrinhos',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (817,'Mucambo',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (818,'Mulungu',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (819,'Nova Olinda',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (820,'Nova Russas',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (821,'Novo Oriente',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (822,'Ocara',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (823,'Orós',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (824,'Pacajus',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (825,'Pacatuba',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (826,'Pacoti',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (827,'Pacujá',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (828,'Palhano',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (829,'Palmácia',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (830,'Paracuru',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (831,'Paraipaba',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (832,'Parambu',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (833,'Paramoti',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (834,'Pedra Branca',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (835,'Penaforte',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (836,'Pentecoste',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (837,'Pereiro',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (838,'Pindoretama',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (839,'Piquet Carneiro',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (840,'Pires Ferreira',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (841,'Poranga',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (842,'Porteiras',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (843,'Potengi',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (844,'Potiretama',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (845,'Quiterianópolis',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (846,'Quixadá',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (847,'Quixelô',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (848,'Quixeramobim',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (849,'Quixeré',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (850,'Redenção',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (851,'Reriutaba',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (852,'Russas',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (853,'Saboeiro',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (854,'Salitre',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (855,'Santa Quitéria',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (856,'Santana do Acaraú',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (857,'Santana do Cariri',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (858,'São Benedito',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (859,'São Gonçalo do Amarante',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (860,'São João do Jaguaribe',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (861,'São Luís do Curu',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (862,'Senador Pompeu',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (863,'Senador Sá',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (864,'Sobral',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (865,'Solonópole',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (866,'Tabuleiro do Norte',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (867,'Tamboril',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (868,'Tarrafas',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (869,'Tauá',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (870,'Tejuçuoca',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (871,'Tianguá',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (872,'Trairi',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (873,'Tururu',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (874,'Ubajara',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (875,'Umari',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (876,'Umirim',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (877,'Uruburetama',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (878,'Uruoca',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (879,'Varjota',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (880,'Várzea Alegre',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (881,'Viçosa do Ceará',6);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (882,'Brasília',7);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (883,'Abadia de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (884,'Abadiânia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (885,'Acreúna',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (886,'Adelândia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (887,'Água Fria de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (888,'Água Limpa',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (889,'Águas Lindas de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (890,'Alexânia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (891,'Aloândia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (892,'Alto Horizonte',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (893,'Alto Paraíso de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (894,'Alvorada do Norte',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (895,'Amaralina',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (896,'Americano do Brasil',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (897,'Amorinópolis',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (898,'Anápolis',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (899,'Anhanguera',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (900,'Anicuns',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (901,'Aparecida de Goiânia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (902,'Aparecida do Rio Doce',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (903,'Aporé',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (904,'Araçu',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (905,'Aragarças',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (906,'Aragoiânia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (907,'Araguapaz',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (908,'Arenópolis',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (909,'Aruanã',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (910,'Aurilândia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (911,'Avelinópolis',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (912,'Baliza',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (913,'Barro Alto',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (914,'Bela Vista de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (915,'Bom Jardim de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (916,'Bom Jesus de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (917,'Bonfinópolis',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (918,'Bonópolis',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (919,'Brazabrantes',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (920,'Britânia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (921,'Buriti Alegre',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (922,'Buriti de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (923,'Buritinópolis',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (924,'Cabeceiras',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (925,'Cachoeira Alta',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (926,'Cachoeira de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (927,'Cachoeira Dourada',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (928,'Caçu',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (929,'Caiapônia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (930,'Caldas Novas',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (931,'Caldazinha',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (932,'Campestre de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (933,'Campinaçu',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (934,'Campinorte',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (935,'Campo Alegre de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (936,'Campo Limpo de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (937,'Campos Belos',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (938,'Campos Verdes',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (939,'Carmo do Rio Verde',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (940,'Castelândia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (941,'Catalão',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (942,'Caturaí',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (943,'Cavalcante',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (944,'Ceres',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (945,'Cezarina',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (946,'Chapadão do Céu',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (947,'Cidade Ocidental',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (948,'Cocalzinho de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (949,'Colinas do Sul',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (950,'Córrego do Ouro',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (951,'Corumbá de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (952,'Corumbaíba',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (953,'Cristalina',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (954,'Cristianópolis',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (955,'Crixás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (956,'Cromínia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (957,'Cumari',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (958,'Damianópolis',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (959,'Damolândia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (960,'Davinópolis',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (961,'Diorama',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (962,'Divinópolis de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (963,'Doverlândia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (964,'Edealina',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (965,'Edéia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (966,'Estrela do Norte',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (967,'Faina',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (968,'Fazenda Nova',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (969,'Firminópolis',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (970,'Flores de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (971,'Formosa',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (972,'Formoso',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (973,'Gameleira de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (974,'Goianápolis',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (975,'Goiandira',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (976,'Goianésia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (977,'Goiânia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (978,'Goianira',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (979,'Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (980,'Goiatuba',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (981,'Gouvelândia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (982,'Guapó',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (983,'Guaraíta',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (984,'Guarani de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (985,'Guarinos',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (986,'Heitoraí',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (987,'Hidrolândia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (988,'Hidrolina',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (989,'Iaciara',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (990,'Inaciolândia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (991,'Indiara',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (992,'Inhumas',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (993,'Ipameri',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (994,'Ipiranga de Goiás',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (995,'Iporá',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (996,'Israelândia',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (997,'Itaberaí',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (998,'Itaguari',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (999,'Itaguaru',9);
INSERT INTO `municipio` (`id`,`nome`,`unidade_federativa_id`) VALUES (1000,'Itajá',9);
